### PR TITLE
Feature/2198/multitool multi select move pages

### PR DESCRIPTION
**Pull request by reecebrowne**
# Description

Drag and drop multiple pages at once using checkboxes

image

Closes #(2198)

## Checklist

- [ X] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [ X] I have performed a self-review of my own code
- [ X] I have attached images of the change if it is UI based
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [ X] My changes generate no new warnings
- [ X] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by Frooodle** [comment]
one weird interaction
select page(s) with multi select, drag them, then clears the select page menu
since its cleared its means you have basically disabled all top buttons even if the user wants to do a rotate all

I think with the usecase of user clicking when selected pages = 0 we have it act as though its not in select mode at all?

**Comment by Frooodle** [comment]
Also do you think its valuable to implement a multi select -direction shift- as well?
Honest question for opinion just typing it before I forget

if you have 2,5,9 selected and you go on one of them and hit the move right one space key should it shift them all one space?
Right now this multiselect it good for grouping pages but not mass shifting them etc

**Comment by reecebrowne** [comment]
>one weird interaction
select page(s) with multi select, drag them, then clears the select page menu (I understand why you want it to clear)
since its cleared its means you have basically disabled all top buttons even if the user wants to do a rotate all
>
>I think with the usecase of user clicking when selected pages = 0 we have it act as though its not in select mode at all?

Agreed that maybe it is a little weird, I think dropping right out of select mode is also a little wonky though. Perhaps retaining now moved pages as checked pages? I wasn't sure either way

> Also do you think its valuable to implement a multi select -direction shift- as well? Honest question for opinion just typing it before I forget
> 
> if you have 2,5,9 selected and you go on one of them and hit the move right one space key should it shift them all one space? Right now this multiselect it good for grouping pages but not mass shifting them etc

Yes 100% agree that other methods would be good and possibly outright better than the drag and drop, I have some ideas for what to do here but decided to make it a 2nd phase so that this initial feature can go out for now.

**Comment by Frooodle** [comment]
> > one weird interaction
> > select page(s) with multi select, drag them, then clears the select page menu (I understand why you want it to clear)
> > since its cleared its means you have basically disabled all top buttons even if the user wants to do a rotate all
> > I think with the usecase of user clicking when selected pages = 0 we have it act as though its not in select mode at all?
> 
> Agreed that maybe it is a little weird, I think dropping right out of select mode is also a little wonky though. Perhaps retaining now moved pages as checked pages? I wasn't sure either way
> 
> > Also do you think its valuable to implement a multi select -direction shift- as well? Honest question for opinion just typing it before I forget
> > if you have 2,5,9 selected and you go on one of them and hit the move right one space key should it shift them all one space? Right now this multiselect it good for grouping pages but not mass shifting them etc
> 
> Yes 100% agree that other methods would be good and possibly outright better than the drag and drop, I have some ideas for what to do here but decided to make it a 2nd phase so that this initial feature can go out for now.

It would break you away if it removed the 'mode' but a user shouldn't click the rotate button and it do nothing 
if there is no selected pages for it to rotate since its empty you should assume the user wants to rotate all pages

**Comment by reecebrowne** [comment]
> > > one weird interaction
> > > select page(s) with multi select, drag them, then clears the select page menu (I understand why you want it to clear)
> > > since its cleared its means you have basically disabled all top buttons even if the user wants to do a rotate all
> > > I think with the usecase of user clicking when selected pages = 0 we have it act as though its not in select mode at all?
> > 
> > 
> > Agreed that maybe it is a little weird, I think dropping right out of select mode is also a little wonky though. Perhaps retaining now moved pages as checked pages? I wasn't sure either way
> > > Also do you think its valuable to implement a multi select -direction shift- as well? Honest question for opinion just typing it before I forget
> > > if you have 2,5,9 selected and you go on one of them and hit the move right one space key should it shift them all one space? Right now this multiselect it good for grouping pages but not mass shifting them etc
> > 
> > 
> > Yes 100% agree that other methods would be good and possibly outright better than the drag and drop, I have some ideas for what to do here but decided to make it a 2nd phase so that this initial feature can go out for now.
> 
> It would break you away if it removed the 'mode' UI but a user shouldn't click the rotate button and it do nothing if there is no selected pages for it to rotate since its empty you should assume the user wants to rotate all pages (but can keep selection UI open I guess?)

Would definitely have to turn off the mode and have them have to re-enter it, Download selected needs to disappear and page break needs to be clear it's going to apply to every page, especially as right now there is no undo for that beyond manually deleting pages.

**Review by Frooodle — APPROVED** [review]

**Pull request merged**
