### PR TITLE
Completed translations for 19 languages using AI

### PR DESCRIPTION
**Pull request by Sf298**
# Description

I created a tool to auto translate .properties files using an open weights LLM model that uses a permissive license (qwen2.5 7b). 
After creating the translations, I manually went through each file to filter out any obviously bad translations (i.e. Chinese characters showing up in the Arabic file).
I did my best to filter out the bad translations but I cannot guarantee their accuracy.
I still chose to submit this PR, because I believe poor spelling/grammar should still be more readable than English for those users that can't read it).

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have attached images of the change if it is UI based
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Review by Frooodle — APPROVED** [review]

**Comment by Frooodle** [comment]
Not done much AI translations before.. will be interesting to hear community feedback on this and if we should do it/stop it in future..
good experiment! Thanks for commit

**Comment by PeterDaveHello** [comment]
Hey @Frooodle @Ludy87 @Sf298,

There are some concerns about using automatic translation, as it can sometimes lead to a poor user experience. Considering that qwen2.5 7b is a relatively small model, using more advanced models like GPT-4o, Claude-3.5-sonnet, or Gemini-2.0 might be a better choice for auto translation.

I noticed that #2166 addressed some AI translation errors, but since this PR involves 19 languages, it might be more effective to use LLM AI translation when translations are severely outdated or neglected or if the existing translations were done with less effective machine translations.

Perhaps considering the use of the more advanced AIs mentioned earlier to review and improve the current translations could help maintain user experience and quality. What do you think?

**Comment by Frooodle** [comment]
This was generally done to pick up on translations that were vastly out of date

We don't intend to ever use generic AI translations again, this was a one time thing due to them being a year out of date 

However yes ones done with better models to improve on the previous ones mistakes would certainly be welcome

**Comment by Frooodle** [comment]
We don't plan on adding automated translations

**Comment by PeterDaveHello** [comment]
I just did a quick analysis of the changes made in this PR by sorting them according to the diff sizes as below:

```
 src/main/resources/messages_hu_HU.properties | 570 +++++++++++++--------------
 src/main/resources/messages_pt_PT.properties | 520 ++++++++++++------------
 src/main/resources/messages_hi_IN.properties | 468 +++++++++++-----------
 src/main/resources/messages_el_GR.properties | 452 ++++++++++-----------
 src/main/resources/messages_ru_RU.properties | 418 ++++++++++----------
 src/main/resources/messages_ko_KR.properties | 384 +++++++++---------
 src/main/resources/messages_cs_CZ.properties | 326 +++++++--------
 src/main/resources/messages_hr_HR.properties | 256 ++++++------
 src/main/resources/messages_nl_NL.properties | 212 +++++-----
 src/main/resources/messages_th_TH.properties | 144 +++----
 src/main/resources/messages_da_DK.properties | 142 +++----
 src/main/resources/messages_ar_AR.properties | 114 +++---
 src/main/resources/messages_fr_FR.properties |  96 ++---
 src/main/resources/messages_sv_SE.properties |  88 ++---
 src/main/resources/messages_id_ID.properties |  72 ++--
 src/main/resources/messages_de_DE.properties |  44 +--
 src/main/resources/messages_es_ES.properties |  34 +-
 src/main/resources/messages_pt_BR.properties |  28 +-
 src/main/resources/messages_it_IT.properties |   4 +-
```

**Comment by PeterDaveHello** [comment]
PR #2549 sent. Please feel free to help review.

**Pull request merged**
