### PR TITLE
Update-helm-chart

### PR DESCRIPTION
**Pull request by sharifm-informatica**
# Description
- update app version in helm chart
- Correct and update UI env variables in chart values

## Checklist:

- [ x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
Really need to automate that versio number..

**Review by Frooodle — APPROVED** [review]

**Comment by Ludy87** [comment]
Hi @Frooodle, is there a dependency on https://github.com/Stirling-Tools/Stirling-PDF/blob/6fc9c7be90a7ab3736dc85bf73cea7403e48b697/build.gradle#L15

**Comment by Frooodle** [comment]
that version number in gradle is what controls the version number everywhere

**Comment by Frooodle** [comment]
yes

**Comment by Ludy87** [comment]
What do you think of this:
https://github.com/Ludy87/Stirling-PDF/blob/sync_versions/.github/workflows/sync_versions.yml
https://github.com/Ludy87/Stirling-PDF/blob/sync_versions/.github/scripts/gradle_to_chart.py

**Comment by Frooodle** [comment]
seems over engineered :P 
but fine by me !

**Comment by Ludy87** [comment]
You can push it yourself, otherwise I need the time resources :P

**Comment by sharifm-informatica** [comment]
Unless we are auto testing the chart deployment, maybe we should not automate the version upgrades. To recap:
- auto tests first
- auto deploy updates to chart second
But I love what you did.

**Comment by Ludy87** [comment]
I have only provided it; I leave the decision to the maintainers of the repo.

**Pull request merged**
