### PR TITLE
Bored waiting button doesnt remove itself after processing (#2079)

### PR DESCRIPTION
**Pull request by alonsofabila-dev**
# Description

hide bored waiting? button after request handling both success and error cases to properly hide the button.

Closes #(2079)

## Images

during request

after delay

after request

after error

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have attached images of the change if it is UI based
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [x] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by Frooodle** [comment]
@DeployPR

**Comment by Frooodle** [comment]
Sorry for using your PR for testing our new automation, we needed a external user

**Comment by Frooodle** [comment]
In the Demo website it seems that the bored waiting button now instantly shows instead of a delay?

**Comment by alonsofabila-dev** [comment]
yes, now the button appear while the request is being processed.

should there be a delay?

**Comment by Frooodle** [comment]
Yes previous logic had a quick delay before showing it

**Comment by alonsofabila-dev** [comment]
I cant find the delay part, do you know where it is?

**Comment by alonsofabila-dev** [comment]
I have corrected the pull request, how should I address the conflicts?

**Comment by Frooodle** [comment]
> I have corrected the pull request, how should I address the conflicts?

however you wish, using githubs built in resolve conflicts UI or locally and push up

**Comment by alonsofabila-dev** [comment]
done

**Comment by alonsofabila-dev** [comment]
what does /deployPR?

**Comment by Frooodle** [comment]
> what does /deployPR?

Deploys it for my testing

**Pull request merged**
