### PR TITLE
refactor: normalize line endings

### PR DESCRIPTION
**Pull request by sbplat**
# Description

Normalize all line endings to LF using `git add --renormalize .`

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Ludy87** [comment]
Hi, if I understand correctly, there are still a few files missing. I get 47 files back, I use another method.

**Comment by sbplat** [comment]
Which ones? If they're binary files, we don't want to touch them.

**Comment by Ludy87** [comment]
```
src/main/resources/messages_ar_AR.properties
src/main/resources/messages_ru_RU.properties
src/main/resources/templates/misc/compare.html
src/main/resources/static/css/general.css
src/main/resources/messages_ca_CA.properties
src/main/resources/templates/convert/book-to-pdf.html
src/main/resources/static/css/merge.css
src/main/resources/templates/split-pdfs.html
src/main/resources/messages_it_IT.properties
src/main/resources/templates/convert/pdf-to-img.html
src/main/resources/templates/misc/auto-rename.html
src/main/resources/static/js/multitool/PdfContainer.js
src/main/resources/templates/misc/stamp.html
src/main/resources/templates/pdf-organizer.html
src/main/resources/templates/convert/url-to-pdf.html
src/main/resources/templates/convert/html-to-pdf.html
src/main/resources/messages_de_DE.properties
src/main/resources/static/css/dark-mode.css
src/main/resources/templates/misc/change-metadata.html
src/main/resources/templates/merge-pdfs.html
src/main/resources/static/js/pipeline.js
src/main/resources/templates/security/add-password.html
src/main/resources/messages_ja_JP.properties
src/main/resources/templates/fragments/footer.html
src/main/resources/messages_sv_SE.properties
src/main/resources/templates/misc/adjust-contrast.html
src/main/resources/templates/security/remove-password.html
src/main/resources/messages_ko_KR.properties
src/main/resources/messages_eu_ES.properties
src/main/resources/templates/security/change-permissions.html
src/main/resources/templates/pipeline.html
src/main/resources/templates/convert/img-to-pdf.html
src/main/resources/templates/convert/pdf-to-html.html
src/main/resources/templates/convert/pdf-to-text.html
src/main/resources/messages_es_ES.properties
src/main/resources/messages_pl_PL.properties
src/main/resources/templates/security/add-watermark.html
src/main/resources/messages_fr_FR.properties
src/main/resources/templates/security/sanitize-pdf.html
src/main/resources/templates/misc/add-page-numbers.html
src/main/resources/templates/crop.html
.gitignore
src/main/resources/static/js/search.js
src/main/resources/templates/fragments/card.html
src/main/resources/templates/rotate-pdf.html
src/main/resources/templates/misc/add-image.html
src/main/resources/messages_zh_CN.properties
```

**Comment by sbplat** [comment]
Thanks for pointing that out!

Created a new PR due to branch protection rules. Superseded by #802.

**Pull request closed without merging**
