### PR TITLE
Fix drag and drop area for file choosers by adding separate ones

### LINKED ISSUE #2367: [Bug]: Dragging and Dropping files appends them to all file choosers in the same page
### Installation Method

None

### The Problem

Dragging and Dropping files appends them to all file choosers in the same page.

### How to reproduce:
1. Go to a page that has multiple file choosers present.
2. Drag and Drop files in the page.
3. Files (or files counter) changes in both file choosers.

In short, Drag and Drop should only affect the target file chooser.

### Version of Stirling-PDF

0.35.0

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

_No response_

### Docker Configuration

_No response_

### Relevant Log Output

_No response_

### Additional Information

_No response_

### Browsers Affected

Firefox, Microsoft Edge

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by omar-ahmed42**
# Description

 - Add separate drag and drop area for file choosers.

### Why?
Previously, when there were multiple file choosers in the same page, if you attempted to drag and drop any files, they would be added to both file choosers as it was designed at first to handle 1 file chooser present, now that we have multiple ones, it is necessary to adapt our design to match the changing functionality.

### Can you not preserve the old overlay when there's only one file chooser present? 
Yes, we can, but imagine as a user, you try to drag and drop a file in one page and the fields turn into drag and drop areas then you go to another page and try to drag and drop again but you encounter the old overlay instead, as a user you might get confused and ask yourself "What changed?" or if a user is telling another user the steps to drag and drop files and he didn't know about this case, then it would still be confusing, thus consistency is preferred in this case.

### UI Change:
Before dragging and dropping:

image

During dragging and dropping:

image

Closes #2367

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have attached images of the change if it is UI based
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [x] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by Frooodle** [comment]
I think we should increase the height of the drag drop area maybe 50-100% more

**Comment by omar-ahmed42** [comment]
I agree that the height should increase, but I feel like 25-50% would be the sweet spot compared to 100% as this going above 50% would require UI changes (possibly tons of margin in between elements) so that it doesn't cover other elements (at 25-50% we would still need to add mb-3 to file choosers and in sign page specifically we would need to add another mt-3 to the box below that contains the type of signature (image, text, etc).

Unless we would redesign our file upload in the first place to look something like

image
(this would placed in a box of course with dashed borders)

this way we could have it any size we want.

If you have any ideas, let me know

**Comment by Frooodle** [comment]
Yeah to be honest i think we could replace the whole file input
have it always be the drag and drop files here box, I think it looks nicer

"Click to upload OR drag and drop" and have it remain as the dotted outlined box version
Probably have it generated a list of files under it which can be manually removed from being selected as well

I think continuing using the Browse inputter is something we should stop

**Comment by omar-ahmed42** [comment]
This is what I went for some far (I might change font colors to go along with the dark/light modes, same goes for the background and the button color, but this is ).

The bottom box should stay hidden unless there are files uploaded.

Each uploaded file should have an icon based on its extension, if it's unknown or we have no icon for it at the moment it should be represented as an empty document icon as in the last icon in the second row.

Each file should have its name displayed (if it's too long then you'll have to hover the name) and the file size (we might convert it to the closest unit, example: files less than 1 MB could be represented as X KBs - where X is the size of the file after conversion - files greater than 1 MB and less than 1 GB would would represented as X MBs and so on).

Why include the name and size and not just "name"? in case more than one file had the same name but different sizes, so that the user can remove the correct one.

Let me know if you have any notes/questions/ideas

image

**Comment by Frooodle** [comment]
I'm very happy with the implementation you described and reasoning

**Comment by omar-ahmed42** [comment]
Awesome! Thanks a lot! I will start pushing my changes so that it would be ready by tomorrow hopefully

**Comment by omar-ahmed42** [comment]
The only thing remaining for me is to take a look at how themeing (dark/light) works in the project, to make the UI change based on the current theme, other than that, I believe it's ready. (It still works with light theme but it doesn't look good, so we would need to adjust that)

**Comment by Frooodle** [comment]
Nice I'll hold off merge and review the current impl

/deploypr

**Comment by omar-ahmed42** [comment]
Finally added support for themeing

## Light theme:

image

image

image


## Dark theme:

image

image

image

**Comment by Frooodle** [comment]
Might be good to have the whole box be clickable instead of just the browse button
and have a on hover event to make the dotted edges bigger/glow etc?

**Comment by omar-ahmed42** [comment]
After making the changes:

### Light:

DragAndDropHoverLightcropped

### Dark:
DragAndDropHoverDarkcropped

I changed the background color on hover as well as adding a box-shadow (glowing effect) on hover, I tried to make the border thicker on hover, but it didn't look good nor smooth when transitioning from thin border to a thicker one, so I went with the glowing effect instead.

> have a on hover event to make the dotted edges bigger/glow etc?

I also removed removed the  browse button and made the entire box clickable as mentioned 

> have the whole box be clickable instead of just the browse button

Let me know if you have any notes/questions/ideas

(The GIF might not be clear due to quality and resolution changes)

**Comment by Frooodle** [comment]
Looks good to me! Speedy work too!
/deploypr

**Review by reecebrowne — APPROVED** [review]

**Comment by reecebrowne** [comment]
image
Just getting the drag and drop window, not the bar of uploaded files, somethings gone wrong there.

Also it does not seem to be compatible with the merge feature

**Comment by omar-ahmed42** [comment]
Can you explain it more?

because this is what I'm getting when I attempt to drag & drop as well as upload a file (1 of them was uploaded by clicking the container and the other one was by drag & drop)

image

The only thing that seems to be not working well is removing files from the vertical list, but not the other way around

**Comment by reecebrowne** [comment]
Is this on your local branch? It's not working on the deployed version here 🔗 Test URL: http://185.252.234.121:2368/     This is running the merged code, so perhaps an issue with the merge?

**Comment by reecebrowne** [comment]
I'll deploy it again just in case there was an issue there. /deploypr

**Comment by reecebrowne** [comment]
image
This is the error I am getting if it helps!

**Comment by Frooodle** [comment]
I think the ideal end goal of this feature would be have it without the preview box for merge but still have the new input box itself (have it togglable)
and then same for multi-tool later down the line in separate PR

**Comment by omar-ahmed42** [comment]
> image This is the error I am getting if it helps!

That's for the error, I believe I understand why It isn't working in your case, it seems that crypto.randomUUID() only works on localhost and over HTTPs which is why it isn't working when deployed, I will what I can do to fix it

**Comment by omar-ahmed42** [comment]
> I think the ideal end goal of this feature would be have it without the preview box for merge but still have the new input box itself (have it togglable) and then same for multi-tool later down the line in separate PR

I feel like we would still need the merge preview box as the user uses it organize/reorder the files (this could be implemented in the box as well, but I feel like clicking "arrow up" or "arrow down" would be easier and more intuitive to the user

**Comment by Frooodle** [comment]
yeah might have not explained it well but that was my thought for merge as well, disable the input boxes preview, but keep merges order toggle

**Comment by omar-ahmed42** [comment]
Now, merge should work successfully, I also fixed the issue where files being removed from merge's list wouldn't reflect in the file chooser.

**Comment by Frooodle** [comment]
> Now, merge should work successfully, I also fixed the issue where files being removed from merge's list wouldn't reflect in the file chooser.

files removed from file choose doesn't reflect in merge list though

**Review by reecebrowne — APPROVED** [review]
All working great now as far as I can tell. Thanks for fixing it so promptly!

**Comment by Frooodle** [comment]
/deploypr 
Brilliant work though, speedy too! thanks again

**Review by Frooodle — APPROVED** [review]

**Comment by omar-ahmed42** [comment]
I believe we forgot to include translations for "Click", "or" and "Drag & Drop"

**Comment by Frooodle** [comment]
good catch!
 if you can add a line to the GB files we have automated script to add to rest of files after merge to dev

**Comment by omar-ahmed42** [comment]
Alright, I will try doing that

**Comment by Frooodle** [comment]
Im also happy to do it in another PR after merge if you are busy :P

lemme know!

**Comment by omar-ahmed42** [comment]
It's totally fine, don't worry, I was just stuck with a bug when I was trying to use translations with pseudo element (::after), turns out there was no bug I just placed th:data-text on the wrong HTML element :D

> if you can add a line to the GB files we have automated script to add to rest of files after merge to dev
Would adding translation to another file besides GB cause issues?

I already added it to messages_en_GB.properties, but I also added it to messages_ar_AR.properties (I haven't yet committed the changes), if this would cause any issues let me know

**Comment by Frooodle** [comment]
nope thats all good!

**Comment by omar-ahmed42** [comment]
You can now merge :D

**Comment by Frooodle** [comment]
Merge conflict with your other PR i think? https://github.com/Stirling-Tools/Stirling-PDF/pull/2365

**Comment by omar-ahmed42** [comment]
> Merge conflict with your other PR i think? #2365

Resolved the conflicts, thanks for letting me know

**Comment by omar-ahmed42** [comment]
I believe this also closes issue #2372

**Pull request merged**
