### PR TITLE
Feature: Undo Redo options multi tool #2297

### LINKED ISSUE #2297: [Feature Request]: Reversion/undo option in multi-tool
### Feature Description

Reversion/undo option in multi-tool 
ctrl-z etc

### Why is this feature valuable?

_No response_

### Suggested Implementation

_No response_

### Additional Information

_No response_

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

### PR DESCRIPTION
**Pull request by omar-ahmed42**
# Description

Multi tool now supports undo/redo options using **CTRL + Z** for undo and **CTRL + Y** for redo.

## Supported operations by undo/redo:
- Rotating a single page.
- Rotating all pages.
- Rotating selected pages.
- Deleting a single page.
- Deleting selected pages.
- Selecting pages.
- Splitting.

Closes #2297

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have attached images of the change if it is UI based
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [x] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by omar-ahmed42** [comment]
I believe file renaming can be implemented but would require modifying the existing code to support debouncing.
Also, there seems to be a bug in inserting a page break, so I delayed implementing undo/redo for it until the bug is resolved (I might submit an issue regarding this bug).

**Comment by Frooodle** [comment]
Great work! and yes please submit bug for page break!

**Review by Frooodle — APPROVED** [review]

**Comment by reecebrowne** [comment]
Splitting doesn't seem to work

**Review by Frooodle — CHANGES_REQUESTED** [review]
Split All pages button doesnt work

**Comment by omar-ahmed42** [comment]
Fixed the split all bug, seems like I forgot to execute split all after introducing UndoManager (Seems like I tested split and forgot to test split all after the changes)

**Comment by omar-ahmed42** [comment]
> The functionality with CTRL+Z is great but could you please add a button for undo too, I would suggest a tooltip on it that tells the user they can also use CTRL+Z. I would suggest this icon https://fonts.google.com/icons?selected=Material+Symbols+Outlined:undo:FILL@0;wght@0;GRAD@0;opsz@24&icon.query=undo&icon.size=24&icon.color=%23e8eaed&icon.platform=web&icon.set=Material+Symbols

I was actually planning on adding a button for undo and another one for redo, but I will start working on it!
Sure, I will try adding a tool tip as well, and I will think of a short appropriate message/note in the tool tip as well

**Comment by reecebrowne** [comment]
> Undo/Redo buttons have been added along with their tool tips, if it looks acceptable to you, then I shall replace hard-coded "Undo" and "Redo" with #{multiTool.undo) and #{multiTool.redo} to support adding translations (should it be a separate pull request or the same one?)

Yeah if you could take a look at the other tooltips on multitool and copy the way they do translations. It's a little awkward.

**Pull request merged**
