### PR TITLE
#1214 Only take pdf that are good for processing

### LINKED ISSUE #1214: Copying multiple files to watchedFolder causes app to grab zero byte files
I copied around 200 PDFs into the watchedFolder, and realized there were more than 350 PDFs in the processing folder which I found weird. Then I saw many of the PDFs are "duplicated" and some of them have "zero bytes" size.

As I suspected the app was starting the process before the files were completely copied over.
I confirmed this by copying only 20 PDFs in the watchedFolder - same behavior.

Wish there was a way to tell the app to wait a bit before processing the file. Similar to the variable PAPERLESS_CONSUMER_INOTIFY_DELAY in paperless-ngx.

### PR DESCRIPTION
**Pull request by kkdlau**
# Description

The current code base allows pipeline directory processor to consume "growing pdf". This is due to file copying is not an atomic operation on computer. Pipeline directory processor then process on those pdf, causing exceptions happen.

This PR implements a FileMonitor, providing ability to check if the pdf files are ready for processing. The pipeline directory processor will only consume those pdfs that are ready for processing.

P.S. A pdf is considered to be ready for processing when there is no more entry event (create, modify, delete) after 0.5s.

Closes #1214

## Checklist:

- [X] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Review by Frooodle — APPROVED** [review]

**Comment by Frooodle** [comment]
image

**Review by Frooodle — CHANGES_REQUESTED** [review]
build failing 
image

**Comment by kkdlau** [comment]
> build failing 
> 
> image
> 
> 

thanks for letting me know 👍🏻
let me check it

**Review by kkdlau — COMMENTED** [review]
updated FIleMonitor - now it accpets a directory that doesnt exists, and only start to monitor the directory if the directory is created

**Pull request merged**
