### PR TITLE
Feature: Show permissions as a separate tab

### LINKED ISSUE #2387: [Feature Request]: Get Info on PDF to show permissions
### Feature Description

Get Info on PDF to show permissions such as editable etc

### Why is this feature valuable?

_No response_

### Suggested Implementation

_No response_

### Additional Information

_No response_

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

### PR DESCRIPTION
**Pull request by omar-ahmed42**
# Description

- Move permissions code into a separate for better readability and maintainability.
- Separate `Permissions` node from `Encryption` so that it would be displayed in the frontend as a separate tab.
- Use more user friendly permission labels such as replacing `canModify` with `Modifying` and values such as `Allowed` and `Not Allowed` instead of `true`, `false`.
- Show permissions regardless of the encryption state.

## Pros of this implementation:
- Less effort displaying the data as it's already ready for display.
- Frontend doesn't need to know much about the business nor the expected values for the data, just more focus on how the data is displayed instead.

## Cons of this implementation:
- Permission labels are different from before.
- Permission labels are not conforming to snake case nor camel case, each word separated by a space instead; requiring users downloading the data as **Json** to input it into their applications to adapt to these changes and maybe even adding extra logic to map the permission labels to their fields (but it's more user friendly).

Closes #2387

Encryption present case:
image

No Encryption present case:
image

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have attached images of the change if it is UI based
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [ ] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by omar-ahmed42** [comment]
I suggest that we separate words in the frontend (regardless of how it's implemented in backend) so that it would be more user friendly, example: EncryptionAlgorithm -> Encryption Algorithm and so on.

**Comment by Frooodle** [comment]
I believe the intent was to have a translation layer enhancement ontop to map those names to the translated message keys in the future 
Hence no spaces etc

**Comment by Frooodle** [comment]
I think this was missed work somewhere down the line and we forgot

**Comment by Frooodle** [comment]
I am happy to merge this PR tho

**Comment by omar-ahmed42** [comment]
Ah, understandable. I can still bring back the old labels/keys, it shouldn't take much time

**Comment by Frooodle** [comment]
That can get picked up in new work whenever it gets done, for now readability Is best :)

**Pull request merged**
