### PR TITLE
Extract tables from PDF to CSV using Tabula

### LINKED ISSUE #1614: [Feature Request]: enhance CSV excel conversion
### Feature Description

use https://github.com/tabulapdf/tabula-java

### Why is this feature valuable?

_No response_

### Suggested Implementation

use https://github.com/tabulapdf/tabula-java

### Additional Information

_No response_

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

### PR DESCRIPTION
**Pull request by omar-ahmed42**
# Description

- Add Tabula dependency to use in extracting tables from PDF files.
- Exclude slf4j-simple from tabula-java dependency as it caused errors in the project when used along with Logback.
- Add FlexibleCSVWriter to allow using different CSVFormat rules, such as quoting all values (i.e: "1", "my value", "my 2nd column value") as CSVWriter's parameterized constructor is protected (thus, we couldn't customize the CSVFormat).
- Utilize Tabula in extracting the table and its values and writing them in CSV format.
- Delete PDFTableStripper as it is no longer needed (Tabula is sufficient).
- Use correct class in the logger present in ExtractCSVController (from CropController.class -to-> ExtractCSVController.class).

Closes #1614

## Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have attached images of the change if it is UI based
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [x] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Comment by Frooodle** [comment]
hmmm need to think about this a lil more
image

**Comment by Frooodle** [comment]
Can you add
implementation ('technology.tabula:tabula:1.0.5') {
    exclude group: "org.slf4j", module: "slf4j-simple"
    exclude group: "org.bouncycastle", module: "bcprov-jdk15on"
}
implementation 'com.google.code.gson:gson:2.8.9'

and see if it still works?

**Comment by Frooodle** [comment]
also did this improve PDF to CSV conversions? any ideas?

**Comment by omar-ahmed42** [comment]
> Can you add implementation ('technology.tabula:tabula:1.0.5') { exclude group: "org.slf4j", module: "slf4j-simple" exclude group: "org.bouncycastle", module: "bcprov-jdk15on" } implementation 'com.google.code.gson:gson:2.8.9'
> 
> and see if it still works?

Sure, I will give it a try and inform you afterwards



> also did this improve PDF to CSV conversions? any ideas?

When I tested it I believe it improved the conversion as the old version would work correctly for some PDF files and fail to work some other files (it would either extract the entire table and place on 1 row - column by column - or would only extract the first 4 values in the first column and also place it in the same line, but in other cases it worked fine), as for tabula I attempted to use it on multiple files including the ones that the old version failed to work on, and it worked correctly/well

**Comment by omar-ahmed42** [comment]
I added the excluded dependencies and added gson as you mentioned
> implementation ('technology.tabula:tabula:1.0.5') {
> exclude group: "org.slf4j", module: "slf4j-simple"
> exclude group: "org.bouncycastle", module: "bcprov-jdk15on"
> }
> implementation 'com.google.code.gson:gson:2.8.9'

but this caused testMainApplicationStartup() in stirling.software.SPDF.SPDFApplicationTest to fail with the following exception `"java.lang.IllegalStateException: java.lang.NoClassDefFoundError: com/google/gson/Strictness"` (I could provide you with the full stack trace if required).

Anyway, so I decided to attempt to run the application without `implementation 'com.google.code.gson:gson:2.8.9'` and it worked well but afterwards I decided to exclude it as well as follows:

```
implementation ('technology.tabula:tabula:1.0.5')  {
        exclude group: "org.slf4j", module: "slf4j-simple"
        exclude group: "org.bouncycastle", module: "bcprov-jdk15on"
        exclude group: "com.google.code.gson", module: "gson"
    }
```

and it also worked pretty well just like before, I guess this way we would be over the security vulnerabilities mentioned earlier. (I will commit it and push it)

If merged I believe this might also close #2255 (when the remote/demo server is updated)

Either way, I found a bug in the UI when trying to convert from PDF to CSV, but I believe I would have to post a separate issue for it

**Pull request merged**
