### PR TITLE
ci: build docker image and healthcheck

### PR DESCRIPTION
**Pull request by nawramm**
Finally got to sit down for a bit and work on this
~~There is a slight overlap between this and #623 which may make this PR unnecessary~~

Closes: #534 

# License Agreement for Contributions
By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under MPL 2.0 (Mozilla Public License Version 2.0) license. 

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
I was just wondering what happened to you doing this i assumed you dropped it and was doing something similar for my local testing planning to eventually migrate it
https://github.com/Stirling-Tools/Stirling-PDF/blob/changes/test.sh

**Comment by Frooodle** [comment]
oh i see you noticed that PR

**Comment by Frooodle** [comment]
Having a dedicated github action for it however is still good, will test and merge this, thanks for the work!

**Comment by Frooodle** [comment]
Was testing using the local testing script i made to try avoid duplication

https://github.com/Stirling-Tools/Stirling-PDF/blob/githubActionTest/.github/workflows/test.yml

**Comment by nawramm** [comment]
Looks good to me, closing${{ steps.versionNumber.outputs.versionNumber }} this PR.

I would suggest changing the versionNumber step to:
```
- name: Get version number
      id: versionNumber
      run: echo "name=versionNumber::$(./gradlew printVersion --quiet | tail -1)" >> "$GITHUB_ENV"
```
Then you can replace `${{ steps.versionNumber.outputs.versionNumber }}` with `$versionNumber`

**Pull request closed without merging**
