### PR TITLE
added a pagingSeal feature to the stamp function

### PR DESCRIPTION
**Pull request by hxlcw**
# Description

I added a `pagingSeal` feature to the stamp function, allowing for seals to ride across page boundaries.

**Main Changes**: 
1. stamp.html 
- I modified the way form elements are shown and hidden, as the addition of the pagingSeal feature increased the number of stamp types to three, making the management of form elements more complex.
- When the type is pagingSeal, here is the page look for:
image

2. StampController
- I added two fields for the `pagingSeal` feature:`pagingPosition` and `firstPageRate`.
- When the stampType is `pagingSeal` , the method will proceed to `addPagingSeal` , which is the new method specifically created for the pagingSeal feature.

**Output Example**:  
image

---

Please feel free to reach out with any questions, concerns, or feedback you may have. I am fully committed to addressing any issues that may arise and ensuring that my contribution aligns seamlessly with the goals and standards of this project.  
  
Thank you again for considering my pull request, and for all the work you do to make this project shine.

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
Looking at your screenshot did you somehow remove the other positions?
image

I don't want to remove functionality

**Comment by hxlcw** [comment]
> Looking at your screenshot did you somehow remove the other positions? image
> 
> I don't want to remove functionality

I didn't remove any functionality or DOM elements. Instead, I copied the same DOM and modified it to suit my functionality.

**Comment by hxlcw** [comment]
> Can you explain how pagingSeal is different to image? Wouldnt pagingSeal just be a image?

The pagingSeal feature crops an image and evenly distributes it along the edges of every page in a PDF, while the image function simply stamps the same image onto each page.

**Comment by Frooodle** [comment]
> > Can you explain how pagingSeal is different to image? Wouldnt pagingSeal just be a image?
> 
> The pagingSeal feature crops an image and evenly distributes it along the edges of every page in a PDF, while the image function simply stamps the same image onto each page.

I think this could be better suited as keeping it just as image
and have a checkbox to "auto crop" the image etc

**Comment by hxlcw** [comment]
> > > Can you explain how pagingSeal is different to image? Wouldnt pagingSeal just be a image?
> > 
> > 
> > The pagingSeal feature crops an image and evenly distributes it along the edges of every page in a PDF, while the image function simply stamps the same image onto each page.
> 
> I think this could be better suited as keeping it just as image and have a checkbox to "auto crop" the image etc can you also explain how this cropping works?

Keeping it as an image type is indeed a good suggestion, and I'll definitely consider it. Here's a more detailed explanation of how the cropping functionality works:

- Scaling and Rotating the Image: The image is first scaled and rotated as necessary using the `stirling.software.SPDF.controller.api.misc.StampController#scaledAndRotationImage ` method.
- Calculating Image Widths: The system calculates the image width for the first page and subsequent pages. If the total image width cannot be divided evenly across all pages, adjustments are made to balance the width, prioritizing the first page if necessary.
- Cropping and Placement: For each page, the adjusted image is cropped and placed within the page boundaries.

**Pull request closed without merging**
