### PR TITLE
further bug fixes when using context path

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

further bug fixes when using context path

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Ludy87** [comment]
before:

image


after:

image


I think it is also future-proof. If you do not agree, you can also reject the PR.

**Comment by Frooodle** [comment]
Seems valid :) 
Just would want client to build path as much as possible Vs server building path 

But I think it makes sense to be safe here

**Review by Frooodle — APPROVED** [review]

**Comment by Frooodle** [comment]
Will quickly test how it plays with nginx before merge

**Comment by Frooodle** [comment]
yeah all seems good! thanks as always

**Pull request merged**
