### PR TITLE
Fix: introduces the verification of the python installation

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

Now it is obvious whether Python is installed or not.

The user gets a better answer.

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
I wonder if instead we should do
https://github.com/Stirling-Tools/Stirling-PDF/issues/820

**Comment by Frooodle** [comment]
Ahh i take it back you basically done this but have it show error rather than disable UI, 
My only thought is should we run this only once at startup and store as var instead of running per command, not much to be gained checking each run

And then we can also add flag to "auto-disable-features-not-installed" or something?

**Comment by Frooodle** [comment]
This could actually be a part of ProcessExecutor since it already is singleton, run check on first command run and then never again..  (or however you want to do it..)

**Comment by Ludy87** [comment]
I hope I understood it correctly :D

**Comment by Frooodle** [comment]
Yeah looks good to me :) 
Might turn it into a multi singleton down the line to support other dependencies but yeah good to merge !

**Review by Frooodle — APPROVED** [review]

**Pull request merged**
