### PR TITLE
visual certificate signing

### LINKED ISSUE #658: re-add visual certificate signing

### LINKED ISSUE #1966: [Bug]: Show Signature in adding signature (PKCS) does not seem to be working.
### Installation Method

Docker

### The Problem

Hi team

The expected way to show the added digital signature is showing a rectangular box like how Adobe shows? 
image

Though the signature is added successfully, it is not visible on the document even after giving all the required fields. I am guessing this is a bug? 
image

### Version of Stirling-PDF

0.29.0

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

https://pdf.zerodha.net/cert-sign

### Docker Configuration

_No response_

### Relevant Log Output

_No response_

### Additional Information

_No response_

### Browsers Affected

_No response_

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by sbplat**
# Description

Add visual digital signatures

Closes #658 and also closes #1966 

## Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### CODE REVIEW

**Review by Frooodle — APPROVED** [review]

**Comment by Thunderbottom** [comment]
Hi, looks like the `signature.png` file does not exist in the docker image. We've tried the latest `alpha` image and we got the following error:

```
Internal Server Error:java.io.FileNotFoundException: class path resource [static/images/signature.png] cannot be resolved to absolute file path because it does not reside in the file system: jar:nested:/app.jar/!BOOT-INF/classes/!/static/images/signature.png
```

**Comment by Frooodle** [comment]
@sbplat  any idea about the signature image and the intent?

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/2141

**Comment by sbplat** [comment]
Added it cause I thought it would be useful to have (it can be changed if needed). Also, we could add an option to disable images.

**Comment by Frooodle** [comment]
right now it seems to fail as that image doesn't exist, was wondering what is intended to be there

**Comment by Frooodle** [comment]
ahh i think its jar build issue vs dev runtime

**Comment by Frooodle** [comment]
``resource.getFile();``
vs
``resource.getInputStream();``

Its not a file when within the jar itself

**Comment by Ludy87** [comment]
```
ClassPathResource resource = new ClassPathResource("static/images/signature.png");
try (InputStream inputStream = resource.getInputStream()) {
    imageFile = File.createTempFile("signature", ".png");
    FileUtils.copyInputStreamToFile(inputStream, imageFile);
} catch (IOException e) {
    logger.error("Failed to load signature image", e);
    throw e;
}
```

maybe even one step further to a tmpfile

**Comment by Frooodle** [comment]
yeah we do same for fonts and things, @Ludy87  looks like you already have the fix? :D

**Comment by Ludy87** [comment]
i don't know if it's a fix, i'm waiting for sbplat, he worked on it, it's just a suggestion. I haven't tested it

**Comment by sbplat** [comment]
Should be fixed now by #2143

**Pull request merged**
