### PR TITLE
Add: Convert PDF to WebP

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

Please provide a summary of the changes, including relevant motivation and context.

Closes #(issue_number)

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
Looks like we can use         PyMuPDF  to do pdfto markdown and others

But also this library seems to have a lot of features... What size does this make the docker 👀

**Comment by Ludy87** [comment]
As always, there are problems when creating

**Comment by Ludy87** [comment]
### linux/amd64

- 1.07 GB

### linux/arm64

- 1.02 GB


@Frooodle It seems to have gotten a bit bigger :) I'll try to press it a little more

**Comment by Ludy87** [comment]
`.github/workflows/pymupdf.yml` must be triggered manually once to build the image - duration 1h
After that it is only triggered when the version in the `.pymupdf` is increased.

The image of latest and fat will increase by about **400-450 MB**, unfortunately it will not be any slimmer

**Comment by Frooodle** [comment]
Okay let me think about this, without more features this is a huge file size jump for us

**Comment by Ludy87** [comment]
I could try to create mujs, but I don't know anything about it :)

**Comment by Ludy87** [comment]
## Stirling Docker size
image

## Test Docker size
image

**Review by Frooodle — APPROVED** [review]

**Pull request merged**
