### PR TITLE
Introduces the checking of message_*.properties

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

This pull request introduces a script to automate the comparison of language files in different branches. The script checks for discrepancies between a reference file and other language files, ensuring consistency in translation keys and values.

- Test 1: Verifies that the number of lines in the files matches between the reference and the current branch.
- Test 2: Checks for missing or extra translation keys between the files.

Immediate Feedback: Provides instant feedback on discrepancies directly in the pull request comments.

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Frooodle** [comment]
Awesome change :D 

Should we also have one to sync between them and raise a PR after merge to main?

**Comment by Ludy87** [comment]
Do you mean missing translations, or in general?

**Comment by Frooodle** [comment]
The missing translations between language so when a user adds to GB it can auto add the others for them maybe PR to PR

**Comment by Ludy87** [comment]
I have to look into how best to do this, as far as I know it is not possible in the PR itself with the bot. But we can definitely handle it like with the version.

**Pull request merged**
