### PR TITLE
Redesign and more

### LINKED ISSUE #929: Menu size issue with some monitor resolutions
Hi,

with the last update that adds the menu **Pipeline** we have noticed that language menu goes out of screen with screen width 1366 pixel:

immagine

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

**_Added_**
**Localization Support:**
Expanded internationalization support by adding new navbar items translations for multiple languages including Arabic, Bulgarian, Catalan, German, Greek, English (UK and US), Spanish, Basque, French, Hindi, Hungarian, Indonesian, Italian, Japanese, Korean, Dutch, Polish, Portuguese (Brazil and Portugal), Romanian, Russian, Serbian (Latin), Swedish, Turkish, Chinese (Simplified and Traditional).

**New SVG Icons:**
Added new SVG icons (license.svg, logout.svg, update.svg, web.svg) to visually represent the newly introduced navbar items.

**CSS Enhancements:**
Introduced new CSS classes in footer.css for dynamic UI elements, improving the visual appeal and interaction of the footer section.

**JavaScript Enhancements:**
Updated favourites.js and githubVersion.js scripts to support new functionalities, including favorites dynamic loading and software update checking.

**UI Enhancements:**
Implemented updates across HTML templates (navbar.html, navbarEntry.html, footer.html, languages.html, home.html, login.html) to incorporate new navbar elements, improving structure, navigation, and accessibility.

_**Removed**_
**Redundant Localization Keys:**
Removed unused localization keys related to "Licenses" navigation, streamlining the properties files.
Changed

**UI Adjustments:**
Refined HTML structure and content across various templates to align with new CSS styling and localization updates.
Enhanced User Experience: Adjusted the home and login pages to integrate new navbar items and icons, enhancing user interaction and overall visual presentation.

_**Fixed**_
**Miscellaneous Fixes:**
Addressed minor UI and localization inconsistencies to ensure a seamless user experience across different languages.

Closes #929

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
Fancy including some screenshots for context on changes?

**Comment by Ludy87** [comment]
### smaller symbols

redesign1

### first and second navigation bar in the home.html (for some languages it is necessary that the image and navbarName are displayed on the second navbar), as well as the tile if an update is available - always in the first place.

redesign2

redesign4

### Some tabs from the navbar have been moved to the footer on all pages - except home.html.

redesign3

**Comment by Frooodle** [comment]
Gonna think about this one and get others opinion, im not sure about it but it could be just because its a change

**Comment by Frooodle** [comment]
Option to hide update notice option for those wanting to stay on a "stable" upgrade version might be nice idea, its a lot more in your face now which has pros and cons for different people

**Comment by Frooodle** [comment]
For the other changes im going send screenshots around and see what people think

**Comment by Ludy87** [comment]
> Option to hide update notice option for those wanting to stay on a "stable" upgrade version might be nice idea, its a lot more in your face now which has pros and cons for different people

I could add a switch that stores a var in localStorage

**Comment by Frooodle** [comment]
> > Option to hide update notice option for those wanting to stay on a "stable" upgrade version might be nice idea, its a lot more in your face now which has pros and cons for different people
> 
> I could add a switch that stores a var in localStorage

Possibly, im thinking in the usecase of a school using something 2 versions behind or something, I dont want to show all students and users this update notice which only applies to the system admin
Might be better as a system var instead of  a per user localStorage

**Comment by Ludy87** [comment]
I like the idea

**Comment by Ludy87** [comment]
It should be hidden here then?

update4

**Pull request closed without merging**
