### PR TITLE
fix: switch to pdftohtml for pdf to html conversions

### LINKED ISSUE #567: pdf 2 html: All on one page.
The pdf content is plain text
docker/latest

image

### PR DESCRIPTION
**Pull request by sbplat**
# Description

Switch from LibreOffice to pdftohtml for PDF to HTML conversions.

Closes #567 

## Checklist:

- [ ] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
is pdftohtml in docker?

**Comment by Frooodle** [comment]
Also sonarcloud can be ignored, its more just for visability to judge yourself if you want to do code changes

**Comment by sbplat** [comment]
> is pdftohtml in docker image?

Not sure. Should add it to be safe.

**Comment by Frooodle** [comment]
I only want to add depending on how large the dependencies are vs the results it has etc

I know the optional install we have of calibre could also support this

**Comment by sbplat** [comment]
The optional install of calibre uses poppler to convert pdf to html, so it should be the same.

**Review by Frooodle — APPROVED** [review]
LGTM

**Pull request merged**
