### PR TITLE
Updated pt_BR ignored translations; Improved pt_BR translation

### PR DESCRIPTION
**Pull request by guinuxbr**
# Description

- Updated pt_BR ignored translations
- Improved pt_BR translation

## Checklist:

- [X] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Review by Frooodle — APPROVED** [review]

**Comment by guinuxbr** [comment]
Hi, @Frooodle. 

I forgot to congratulate you and the Stirling-PDF community for such a great piece of software.

Thank you!

**Comment by Ludy87** [comment]
hi @guinuxbr!

Thank you for your help in improving it.

in your messages_pt_BR.properties parts of the translations are missing such as: invalidPasswordMessage, disabledCurrentUserMessage etc.
There are also several empty lines missing that must be strictly adhered to in order to pass a consistency analysis.

**Comment by guinuxbr** [comment]
Oh, I'm sorry to hear that.

I was unaware that the blank lines are essential. I guess my IDE formatted it when I saved it. I'll double-check and re-add the blank lines.

I'll also check the strings you mentioned. I thought I had translated all of them.

Should I fix and create a new PR?

**Comment by Ludy87** [comment]
The PR is clear, so it should not be a problem to just change it.

**Comment by guinuxbr** [comment]
I fixed the blank lines issue.
Regarding the strings "invalidPasswordMessage" and "disabledCurrentUserMessage", I was unable to find both within any "messages_xx_XX.properties". Please let me know if something else needs to be fixed.

**Comment by Frooodle** [comment]
> I fixed the blank lines issue. Regarding the strings "invalidPasswordMessage" and "disabledCurrentUserMessage", I was unable to find both within any "messages_xx_XX.properties". Please let me know if something else needs to be fixed.

https://github.com/Stirling-Tools/Stirling-PDF/blob/fa0152aa2db61d00cd5be70b4fe3cec3b8bb8e04/src/main/resources/messages_en_US.properties#L63

I think you need to pull latest main branch

**Comment by guinuxbr** [comment]
I've tried again. It should be correct now 🙂.

**Review by Frooodle — APPROVED** [review]

**Pull request merged**
