### PR TITLE
[Fix]: Multi tool card height and width

### LINKED ISSUE #1857: [CSS Bug]: Card length & width should be expanded dynamically in PDF Multi tool
### Installation Method

Docker

### The Problem

image

### Version of Stirling-PDF

0.28.3

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

http://localhost:8080/multi-tool

### Docker Configuration

_No response_

### Relevant Log Output

_No response_

### Additional Information

_No response_

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by HardikaZalavadia**
# Description
Fixes the width of the Multi Tool card.

Closes #1857 

PDF multiTool

PDF Multitool-1

### CODE REVIEW

**Comment by Frooodle** [comment]
Hmm i Dont think i actually agree with this issue ticket in first place, reducing this size makes it near unusable

**Comment by HardikaZalavadia** [comment]
Hii frooodle,

I just want to brief idea of issue  #1857, what changes do you need?

**Comment by Frooodle** [comment]
I dont believe its a valid issue ticket, although other pages should be aligned with a set size throughout the website, this pdf multi tool is unique, handles multiple pages and needs the additional sizing that it has.
As such I don't believe that ticket does need to exist and I have closed it

**Comment by HardikaZalavadia** [comment]
okay, I got your point. Thank you

**Pull request closed without merging**
