### PR TITLE
Languages

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

Removed several spaces, added missing strings for German, corrected typos

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
Appreciate these changes and the ones that keep coming, am i good to merge?

**Review by Frooodle — APPROVED** [review]

**Comment by Ludy87** [comment]
I still have a few corrections, if you want I can also open a new PR for it and you can merge them here.

**Comment by Ludy87** [comment]
@Frooodle Sorry for the offtopic, but can you tell me why `action="/api/v1/general/crop"` and `th:action="@{api/v1/misc/auto-split-pdf}"` exist ?
You can merge the PR, thanks.

**Comment by Frooodle** [comment]
Not sure what you mean by the question, like what purpose do they serve and what do they do to the document or...?

**Comment by Ludy87** [comment]
I don't see any guideline why one should work with `@{...}` expression and one without.

**Comment by Frooodle** [comment]
Ahh right so thymeleaf one does some extra things 
When just used with 2 static plain text entries it still functions differently 

For instance it can auto add context paths and other things 
Why I switch between them... I shouldn't 
This must be when I was testing which to use 

One is faster to use
 one is more flexible with weird nginx paths 

Still never decided but generally they function same

**Comment by Ludy87** [comment]
It drove me crazy, I can't deal with it. Maybe a constant line should be established to avoid any confusion (on my part :-D).

**Comment by Frooodle** [comment]
Yeah certainly should be constant throughout

**Comment by Frooodle** [comment]
oh man those conflicts :(

**Comment by sbplat** [comment]
Thanks!

**Pull request merged**
