### PR TITLE
HTML, CSS, JS and JAVA corrections

### PR DESCRIPTION
**Pull request by Ludy87**
# Description

- Missing HTML tags were added and the style was adjusted.
- The currentPage attribute was added for login and account in the AccountWebController.
- Darkmode.js has been adapted for the drop-down menu in the login.
- The style sheet for outsourced to files.

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

### CODE REVIEW

**Comment by Frooodle** [comment]
You give me some nightmare PRs to review 😂

**Comment by Ludy87** [comment]
I can't help it, it's like an accident, I just couldn't look away. But I need another day or two to correct things.

**Comment by Frooodle** [comment]
Generally speaking raising a PR before changes are finished isnt the best, It sends us all emails but it also uses up the free minutes on the github action bots
OSS software only gets a set amount of free github action server time per month

**Comment by Ludy87** [comment]
Sorry I used up your resources and flooded your email inbox.

The PR is ready to be audited.

**Review by Frooodle — APPROVED** [review]

**Pull request merged**
